[package]
name = "katarl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
env_logger = "0.11.8"
log = "0.4.27"
midir = "0.10.1"
parse_duration = "2.1.1"
serde = { version = "1.0.215", features = ["serde_derive"] }
signal-hook = "0.3.17"
toml = "0.8.19"
xdg = "2.5.2"
